Fix overloading config and missing id in response
MarketSquare/robotframework-webservice pull request #35
Opened 2024-01-15 06:05 UTC by remi-picard

It was impossible to overload the config of the server.

I run the server on my local machines (Windows and MacOs) with options :
```bash
# taskfolder not overloaded
python -m RobotFrameworkService.main -p 5003 -t path_to_my_taskfolder
# variablefiles not overloaded
python -m RobotFrameworkService.main -p 5003 -V examples\environment.py
```
In `RobotFrameworkService/routers/robotframework.py` : `RFS_Config().cmd_args` is always `DefaultConfig`

The fix is to move up the call of `config=RFS_Config().cmd_args` in the async router method. I imagine that coroutines like `_start_specific_robot_task` are valued before execution and so they get the default value of `RFS_Config`.

There is another fix, in a second commit, for returning the id of test run.

2024-01-22 21:02 UTC, Noordsestern reviewed
Looks good! I only have basically 2 questions about design changes. but overall this looks like an improvement. Thank you!

2024-01-22 21:02 UTC, Noordsestern commented on RobotFrameworkService/routers/robotframework.py
> +def _start_specific_robot_suite(id: str, suite: str, variables: list, config) -> int:
same as above, marked for later tracability: Why do we make variables a mandatory argument?

2024-01-22 21:02 UTC, Noordsestern commented on RobotFrameworkService/routers/robotframework.py
> +def _start_specific_robot_task(id: str, task: str, variables: list, config) -> int:
same as above, marked for later tracability: Why do we make variables a mandatory argument?

2024-01-22 21:02 UTC, Noordsestern commented on RobotFrameworkService/routers/robotframework.py
> -import threading
thanks!

2024-01-24 17:13 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> -        kwargs={"id": id, "task": task, "variables": variables},
I switched from kwargs to args to prepare the 2nd commit.

The idea is also to standardize the method signatures of `run_robot_and_wait` and `run_robot_in_background` and callback functions `func`. All these method use only `args`.
Moreover, the first args is always `id`. That is why I can do `id = args[0]` in 2nd commit.

Another solution for the 2nd commit (without `args[0]`),  could also adding `id` in the signature of `run_robot_and_wait`.
For example : 
````python
# Add id in 2nd argument
async def run_robot_and_wait(executor: Executor, id: int, func, args):
    #  ...
    result: int = await loop.run_in_executor(executor, func, *args)
    if result == 0:
        #  ...
        result_page += f'<p><a href="/logs/{id}/log.html">Go to log</a></p>'
    #  ...

# Calling method
response = await run_robot_and_wait(request.app.state.executor, id, func=_start_all_robot_tasks, args=[id, None, config])
```

2024-01-24 17:20 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +def _start_all_robot_tasks(id: str, variables: list, config) -> int:
You are right : `variables` is always `None`. I will remove `variables` from `_start_all_robot_tasks`.

2024-01-24 17:24 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +def _start_specific_robot_suite(id: str, suite: str, variables: list, config) -> int:
This time, `variables` is always passed with `_start_specific_robot_suite` method. I think it should be mandatory.

Examples : 

```python
@router.get("/run/suite/{suite}", tags=["execution"])
async def run_suite(suite, request: Request):
    #...
    variables = RequestHelper.parse_variables_from_query(request)
    #...
    response = await run_robot_and_wait(
        request.app.state.executor,
        func=_start_specific_robot_suite,
        args=[id, suite, variables, config],
    )
```

2024-01-24 17:25 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +def _start_specific_robot_task(id: str, task: str, variables: list, config) -> int:
`variables` is always passed with `_start_specific_robot_task` method. I think it should be mandatory.

2024-01-31 19:13 UTC, Noordsestern requested changes
Looks good! I agree with you on the suggested changes about the variables parameter and the obsolete lines.

2024-02-02 06:30 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +def _start_all_robot_tasks(id: str, variables: list, config) -> int:
I have pushed the changes

2024-02-02 06:30 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +def _start_specific_robot_suite(id: str, suite: str, variables: list, config) -> int:
I have pushed the changes

2024-02-02 06:30 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +def _start_specific_robot_task(id: str, task: str, variables: list, config) -> int:
I have pushed the changes

2024-02-18 09:57 UTC, Noordsestern approved these changes
LGTM

2024-02-18 09:58 UTC, merged