Add API POST /robotframework/run
MarketSquare/robotframework-webservice pull request #37
Opened 2024-01-22 17:34 UTC by remi-picard

I suggest to add a new generic API POST endpoint to handle all possible robot CLI options (running test, task, suite... or overloading variables or changing loglevel... eventualy all possibles robot options).

Execution can be synchronous or asynchronous.

For example :

![image](https://github.com/MarketSquare/robotframework-webservice/assets/7821550/480b2677-1123-44dd-ab20-05afb2a215fb)

Options implemented (Swagger Schema) : 

![image](https://github.com/MarketSquare/robotframework-webservice/assets/7821550/d1c04a80-247e-499c-92fe-d81f78cf533c)

Examples in Swagger :

![image](https://github.com/MarketSquare/robotframework-webservice/assets/7821550/f97a4adb-1bd2-444d-a155-a139e6416d2c)

Old execution GET API could be deprecated :
![image](https://github.com/MarketSquare/robotframework-webservice/assets/7821550/048548ac-a63b-4fdd-8420-9c14f6e87c03)

2024-02-01 06:31 UTC, JianZhou12345678 commented
Wow, that's great. It's exactly what I need. Thank you very much

2024-02-18 10:06 UTC, Noordsestern requested changes
Great idea! I rather not deprecate the GET endpoints, though. Other than that, I think, these changes should be merged and improve the webservice. Thank you :1st_place_medal:

2024-02-18 10:06 UTC, Noordsestern commented on RobotFrameworkService/routers/robotframework.py
> +@router.get("/run/all", tags=["execution"], deprecated=True)
I would not like to deprecate the GET endpoint. With POST we always need a body which requires a bit logistics on the client side. GET is simply calling an URL.

I know it is only convenience and debatable if GET is meant for triggering an action. But it was very useful for me when hosting robot-werservice in Google Cloud Run.

I would like to keep GET and add the POST endpoint

2024-02-18 12:41 UTC, remi-picard commented
> Great idea! I rather not deprecate the GET endpoints, though. Other than that, I think, these changes should be merged and improve the webservice. Thank you 🥇

Ok, no problem, I remove the deprecation changes.

2024-02-18 12:42 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework.py
> +@router.get("/run/all", tags=["execution"], deprecated=True)
I have just removed that.

2024-02-18 13:09 UTC, Noordsestern requested changes

2024-02-18 13:09 UTC, Noordsestern commented on RobotFrameworkService/routers/robotframework_run.py
> +from typing import Annotated
The import of `Annotated` seems to break with Python < 3.10 

I am fine with dropping support for Python 3.7, since it is end-of-lie. I am not so sure though about dropping support for 3.8 and 3.9.

Can we make this somehow compatible with 3.8?

2024-02-18 13:27 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework_run.py
> +from typing import Annotated
You are right, there are some incompatibilities with Python < 3.10.

For example, I have to change import `typing` to `typing_extensions` (https://fastapi.tiangolo.com/python-types/#__tabbed_8_2)

I will try to fix 3.8 and 3.9.

2024-02-18 13:45 UTC, remi-picard commented on RobotFrameworkService/routers/robotframework_run.py
> +from typing import Annotated
It is OK, I also change `|` with `Optional` (https://fastapi.tiangolo.com/python-types/#using-union-or-optional)

FastAPI is really well documentated !

2024-02-18 19:22 UTC, Noordsestern approved these changes

2024-02-18 19:22 UTC, merged